### ISSUE TITLE
Service Failed to Build - Key Not Found

### ISSUE THREAD

**Issue by grassroot2013** [realpage/lumen-starter#100]
Step 5 : RUN apk add --update --no-cache git zip unzip     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in 001d4ccb18a7
ERROR: Service 'fpm' failed to build: failed to update store for object type *libnetwork.endpointCnt: Key not found in store
--------------

I also got this at one point for the db as well. Please help!

**Comment by bkuhl** [comment]
Try running this again.  I imagine this could be a temporary problem.

**Comment by grassroot2013** [comment]
Yes I think it was. Thanks for your response. I also removed : "/var/lib/docker/network/files/local-kv.db" and restarted docker and it ran after that. I read that the local-kv.db could have gotten corrupted.
