### ISSUE TITLE
JsonAPI Integration Concern: Content-Type

### ISSUE THREAD

**Issue by meareg** [realpage/lumen-starter#37]
In one of the Enterprise Service team meetings, we talked about the JSON API integration. There were concerns about the Content-Type and the data structure specified in http://jsonapi.org/. We are concerned about external applications and APIs consuming our enterprise API build on this spec as it is not following the regular application/json content type, for example.

**Comment by bkuhl** [comment]
If there are specific concerns, lets please address them one by one in separate issues.  For this case, The `application/vnd.api+json` header follows the [naming convention for Media Types](https://en.wikipedia.org/wiki/Media_type#Naming) and has been officially registered with the [IANA](http://jsonapi.org/#mime-types).  Any additional information you can provide about the concern would help us consider challenges we may face in the future.

**Comment by bkuhl** [comment]
This specific header doesn't just indicate it's a JSON response, but a json-api response.  It's more specific than `application/json`.

**Comment by bkuhl** [comment]
Is there anymore to discuss here or should we close this out?

**Comment by bkuhl** [comment]
I'm going to go ahead and close this out.
