### ISSUE TITLE
API url structure & Versioning

### ISSUE THREAD

**Issue by AnitaYip** [realpage/lumen-starter#53]
Currently, lumen-starter project assumes the structure of /api/v1 as a prefix to the API urls. Since these are enterprise services that we are trying to build, can we just leave the urls to follow REST convention? And for versioning, can we use request headers instead of api url to declare the versioning? This will help the service providers to define the default version for the APIs.

**Comment by bkuhl** [comment]
We'd love to chat about this further... this is one area we didn't give extensive thought and your inquiry has caused us to investigate more.  http://www.lexicalscope.com/blog/2012/03/12/how-are-rest-apis-versioned/ contains a decent index of various discussions around the web on this topic.

**Comment by bkuhl** [comment]
After reading some of the articles in the link I posted, I talked with John and David and we definitely agree that versioning in headers is ideal over versioning in the URLs.  Thanks for bringing this up!

Middleware to assist with version handling should probably be added to https://github.com/realpage/json-api-for-lumen (which is already included in the lumen-starter) and then implemented in the lumen-starter.

**Comment by AnitaYip** [comment]
Not sure if json-api-for-lumen is the right place for adding versioning. Agree that versioning may require minimal changes that creating a new package for that may not be very appealing, but if it is added to the json-api-for-lumen, the package name will no longer be self explanatory of what it does. Just a thought. Don't have any better ideas either.

**Comment by bkuhl** [comment]
I'm including @johnfischelli, @mabon and @mh3720 on this because they may have some insight.  Have you guys investigated how to handle versioning these APIs?

**Comment by libasoles** [comment]
I'm late on this, but what's the current status of api versioning via headers? Can't find a single tutorial on this.

**Comment by bkuhl** [comment]
We haven't come across a package that assists with this, but it's essentially the idea of defining the version number in the header of the request/response.  There's not currently an implementation of this in the lumen-starter.

**Comment by slone** [comment]
Hi, I just started looking for information about API versioning with Lumen (that's how I ended up here) and I thought I would share that the Dingo package seems to provide versioning management. See at the bottom of [this page](https://vea.re/blog/150905-api-with-dingo-and-lumen-part-1)
I'm just discovering this Dingo package, but I guess installing it might be a bit overkill in most cases.
