### ISSUE TITLE
Accessing a custom package that is a private github repo is failing

### ISSUE THREAD

**Issue by AnitaYip** [realpage/lumen-starter#58]
I have created a custom package with the common code to be used by all the enterprise services as a private github repo- [enterprise-services-base](https://github.com/realpage-property-os/enterprise-services-base). When I add this as a dependency in property-api, the build failed with the below error. As we build multiple applications for each domain, we will have lot of common code, that we duplicate in each of this repo. Can you please look into this issue? Let me know if you suggest to go with public repo for custom packages instead.

> [RuntimeException]                                                                                                              
  Failed to clone https://github.com/realpage-property-os/enterprise-services-base via https, ssh protocols, aborting.            
  - https://github.com/realpage-property-os/enterprise-services-base                                                              
    Cloning into bare repository '/root/.composer/cache/vcs/https---github.com-realpage-property-os-enterprise-services-base'...  
    remote: Invalid username or password.                                                                                         
    fatal: Authentication failed for 'https://github.com/realpage-property-os/enterprise-services-base/'                          
  - git@github.com:realpage-property-os/enterprise-services-base                                                                  
    Cloning into bare repository '/root/.composer/cache/vcs/https---github.com-realpage-property-os-enterprise-services-base'...  
    Host key verification failed.                                                                                                 
    fatal: Could not read from remote repository.                                                                                 
    Please make sure you have the correct access rights                                                                           
    and the repository exists.                        

Here is the Travis build link - https://travis-ci.com/realpage-property-os/property-api/builds/26391284

**Comment by jlaswell** [comment]
Travis does not have access to the `realpage-property-os/enterprise-service-base` repo, and so it is unable to authenticate when trying to clone the project. I think that we need to pull the functionality in that package directly into the `property-api` project to resolve this. Also, an `enterprise-service-base` concept will need to be under the `realpage` namespace, rather than the `realpage-property-os` namespace. We'll look at what needs to happen to start something that we can all contribute to there.

**Comment by AnitaYip** [comment]
I did pull the code into property-api for now, for the build to pass. But I will need the same code in a different repo now. Surely, I will add the code there as well for the time being. But its duplicate code. Considering we will have different repositories for each domain under enterprise services, we will end up lot of repositories and this code will be replicated everywhere.

I did modify the namespace to be under Realpage, unless you are referring to moving it under Realpage organization in github. Either way, I am ok with it, though I am not entirely sure that it will be used anywhere other than these enterprise services under Realpage-property-os

**Comment by bkuhl** [comment]
Is there a reason we wouldn't open source `enterprise-service-base`?

**Comment by AnitaYip** [comment]
I guess, since it is created as a private repo initially, even after changing it to public repo, I was still not able to clone this repo during Travis build. I had to add a personal access key to the composer.json of my api repos to be able to access this one. That's why I changed it back to private, at least until I have the time to figure out a workaround or create a brand new public repo and port all the code into that.

**Comment by AnitaYip** [comment]
The token added to the public repo was already invalidated. For the private repos, it is a new token. If you want that to be deleted as well, please let me know if you have any work around to connect from Travis or if you suggest creating a new public repo and port the code on to that and delete the current one

**Comment by mabon** [comment]
Is this issue resolved @AnitaYip / @bkuhl ?

**Comment by AnitaYip** [comment]
Hey Ben, not sure why you closed this, but we are still using a personalized access token in the composer.json to access private repos from travis

**Comment by bkuhl** [comment]
Gotcha.  The way to proceed would be to review the [Private Dependencies](https://docs.travis-ci.com/user/private-dependencies/) section of the travis docs as they list a few options to avoid this.

**Comment by bkuhl** [comment]
I'd recommend the Deploy key route.

**Comment by AnitaYip** [comment]
Thanks Ben, Will try that one.
